rm(list = ls(all.names = TRUE))
hist(faithful[,2])
hist(iris3[,1,1])
pdf("qqplot.pdf", width = 4.5, height = 7)
par(mfrow = c(2, 1), cex = 0.4)
qqnorm(faithful[,2], main="Waiting time between Old Faithful eruptions")
qqline(faithful[,2])
qqnorm(iris3[,1,1], main="Sepal length of setosa irises on the Gaspe Peninsula")
qqline(iris3[,1,1])
dev.off()